
name: commitSchedule

on:
  push:
    paths:
      - '.github/**'
  schedule:
    - cron: "15 08 * * *"

jobs:
  autoCommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: commit & push
        run: echo $((RANDOM % 20)) && ./main --amount $_ --with-push
#        run: git status
        shell: bash
