
name: commitSchedule

on:
  push:
    branches:
      - master
  schedule:
    - cron: "15 08 * * *"

jobs:
  autoCommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
      - name: commit & push
        run: ./auto-commit.sh
        shell: bash
