
name: commitSchedule

on:
  push:
    paths:
      - '.github/**'
  schedule:
    - cron: "15 08 * * *"

jobs:
  configGit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set git user
        run: git config user.email "gofer_bot@example.com" && git config user.name "Gopher-BOT"

  autoCommit:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: commit & push
          run: echo $((RANDOM % 20)) && ./main --amount $_ --with-push
  #        run: git status
          shell: bash
